######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 19 19:11:24 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += include.h mainwindow.h matrix.h rdarray.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp matrix.cpp rdarray.cpp
